[package]
name = "toy-cli"
version = "0.1.0"
edition = "2021"
authors = ["jason tian <18215513386@163.com>"]


[dependencies]
anyhow = "1.0.90"
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
